name: Test against supported python versions

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - 'main'
  pull_request:
    branches: [ main]

jobs:

  test-3:
    name: test
    uses: adrybakov/vegrofi/.github/workflows/tests.yml@main
    with:
      python-version: '3.x'
